version : '3'

services:
    db:
        image: postgres:11
        ports:
            - "5432:5432"
        environment:
            - "POSTGRES_USER=postgres"
            - "POSTGRES_DB=DBName"
            - "POSTGRES_PASSWORD=postgres"

        volumes:
            - postgres_data:/var/lib/postgresql/data/
    web:
        image: final
        ports: 
            - "8000:8000"
        command: gunicorn -b :8000 -w 3 newsapi.wsgi
        depends_on:
            - db
volumes:
    postgres_data: